model_list:
  - model_name: fable-5
    litellm_params:
      model: anthropic/claude-3-5-sonnet-20241022
      api_key: "os.environ/ANTHROPIC_API_KEY"

general_settings:
  master_key: "sk-master-key-for-gateway"
  database_url: "postgresql://neondb_owner:npg_y9qASTz6mjsW@ep-gentle-tooth-ato5a2fc-pooler.c-9.us-east-1.aws.neon.tech/neondb?channel_binding=require&sslmode=require"
